## Vectorization

- 왜 벡터화를 진행하는 걸까?
딥러닝에서는 많은 훈련 예제가 존재하는 데 이를 for-loop를 사용해서 훈련시키는 것은 비효율적이다. 그래서 이를 해결하는 방법으로 **벡터화**를 진행한다.

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


### 벡터화 vs 비벡터화

- 아래 예제를 통해 numpy를 사용한 벡터화가 for-loop를 사용한 비벡터화보다 큰 차이로 빠르다는 것을 확인할 수 있다. 이는 많은 훈련 예제가 존재한다면 격차는 더 커질 것이다.

In [6]:
# 벡터화 예제
import time

a = np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("vectorized version: " + str(1000*(toc-tic)) + "ms")

vectorized version: 0.3409385681152344ms


In [8]:
# 비벡터화 예제
c = 0
tic = time.time()
for i in range(100000):
    c += a[i]*b[i]
toc = time.time()

print("for-loop: " + str(1000*(toc-tic)) + "ms")

for-loop: 44.33393478393555ms


## More vectorization examples

- 명심할 것은 for-loop를 피해야한다는 것이다.
- numpy의 내장함수를 잘 활용하자

#### Logistic regression derivatives vectorization 구현

![./images/1.png](./images/1.png)

![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.03.58.png](./images/2.png)   

여기서 왜 dZ를 전치하였을까? 다음 식을 보면 알겠지만, 최종적인 형태를 맞추기 위해서 dZ 전치를 수행

#### Implementing
![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.05.21.png](./images/3.png)   
해당 과정을 여러 번의 기울기 하강(Gradient descent)위해서는 for-loop가 필요할 수 있다.

## Broadcasting in Python

![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.28.09.png](./images/4.png)

![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.30.19.png](./images/5.png)

In [2]:
import numpy as np

A = np.array([[56.0 ,0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
# 브로드 캐스팅 예시
# A/cal.reshape(1,4)를 안 해줘도 된다
# 어떻게 A(3,4)와 cal(1,4)계산이 가능한가? Broadcasting!
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Python, numpy vectors

In [9]:
# 1차원 배열, 해당 배열을 사용하지 않기 
a = np.random.randn(5)
print(a.shape)

(5,)


In [10]:
# 해당 방식으로 배열 생성 권장
a = np.random.randn(5,1)
print(a.shape)

(5, 1)


In [11]:
# assert를 사용하여 차원 명시 
assert(a.shape == (5,1))